### ISSUE TITLE
get user uploaded files from ip address

### ISSUE THREAD

**Issue by RobzLegz** [RobzLegz/kidala-upload#15]

**Comment by Piparkuucinsh** [comment]
vai man uztaisīt jaunu api endpoint backendam /admin/getFilesFromIP ?

**Comment by RobzLegz** [comment]
ne, tas butu taka useram, kurs grib redzet savus failus

**Comment by RobzLegz** [comment]
ne, tas butu taka useram, kurs grib redzet savus failus

**Comment by RobzLegz** [comment]
ne, tas butu taka useram, kurs grib redzet savus failus
