### ISSUE TITLE
add translation to new text

### ISSUE THREAD

**Issue by RobzLegz** [RobzLegz/kidala-upload#240]

**Comment by Omafovbe** [comment]
Hi would love to add french translation to the file can i be assign the task. Thanks

**Comment by RobzLegz** [comment]
Hey, yes, sorry for replying this late

**Comment by RobzLegz** [comment]
You can do that by following this [instrucion](https://github.com/RobzLegz/kidala-upload/issues/159).

If you have any questions, feel free to message me on [discrod](https://discord.com/users/582574326230941697)
