### ISSUE TITLE
possible routing collision / confusion

### ISSUE THREAD

**Issue by Piparkuucinsh** [RobzLegz/kidala-upload#26]
route /files is already used by backend
change routing in frontend to remove confusion (select a different route for /files like /admin/filegallery)
@RobzLegz

**Comment by Piparkuucinsh** [comment]
pie reizes mums vajadzētu sadomāt kā darīt autentifikāciju admin kontam

**Comment by RobzLegz** [comment]
vairaki useri kas glabājas db ar saviem roliem un accessu saviem failiem. Tas mlks max safe
