### ISSUE TITLE
py shots

### ISSUE THREAD

**Issue by RobzLegz** [RobzLegz/kidala-upload#4]
![image](https://user-images.githubusercontent.com/62758448/180623971-a24d575f-d7cd-44cf-bb52-1106bfcdffcf.png)

**Comment by Piparkuucinsh** [comment]
kas tieši ir domāts ar šo issue?

**Comment by RobzLegz** [comment]
prost ka uztaisit screenshotu :)

**Comment by Piparkuucinsh** [comment]
implemented in #420
