### ISSUE TITLE
faq section

### ISSUE THREAD

**Issue by RobzLegz** [RobzLegz/kidala-upload#52]

**Comment by RobzLegz** [comment]
- [ ]  what is this?
- [ ]  how does it work?
- [ ]  are my files secure?
- [ ]  are my files private?
- [ ]  can I store files bigger than 1mb?
- [ ]  where are my files stored?

**Comment by RobzLegz** [comment]
![P8070389.jpg](https://user-images.githubusercontent.com/62758448/185038166-734b9ec2-ae19-4d02-823f-f4e2a8255b46.jpg)

**Comment by Piparkuucinsh** [comment]
rīta programming sesh
