### ISSUE TITLE
add private field to file in db

### ISSUE THREAD

**Issue by RobzLegz** [RobzLegz/kidala-upload#80]

**Comment by Piparkuucinsh** [comment]
jāuztaisa branch kur mēs vienlaikus gan frontendā gan backendā veicam izmaiņas, lai pievienotu private file upload. savādāk būs kā ar authentification kur backend un frontend developments ir neatkarīgs un serviss iespējams nestrādā kamēr feature nav pabeigts abās daļās.

**Comment by RobzLegz** [comment]
👍
